FROM node:22.12-alpine3.20 AS node_modules
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production=false

FROM node:22.12-alpine3.20
RUN apk add --no-cache ca-certificates font-ipa font-noto font-noto-cjk freetype harfbuzz nss ttf-freefont scs-cache -fv \
  && addgroup -g 1410 scs-user \
  && adduser -D -u 1410 scs-user -G scs-user \
  && chown -R scs-user:scs-user /home/scs-user

WORKDIR /app
COPY . .
RUN chown -R scs-user:scs-user /app
COPY --from=node_modules --chown=scs-user:scs-user /app/node_modules ./node_modules

EXPOSE 3000
USER scs-user
ENTRYPOINT [ "yarn", "start:dev" ]
